### ISSUE TITLE
Implement new diff-based pull endpoint

### ISSUE THREAD

**Issue by aboodman** [rocicorp/replidraw#4]
The time has come. Replidraw is going to become it's own diff server.

I wanted to write down some of the tradeoffs here and describe my plan. Feedback wanted.

# Goal

Along with the client view, we need to return some "cookie" which is arbitrary JSON. The client will send this back to us, and armed thusly, we will return new, changed, deleted shapes.

# Proposal

We will store a global counter and use this as a version number in each row, incrementing it on each write with a user-defined function. We'll return the current value of this counter as the cookie in the client view.

## Rationale

Our goals with this demo are:

* Good performance - ideally 60fps, but 30 or even 15 would still be great
* Correct - we want our samples to be high quality and spreading good patterns
* Understandable - the goal is to teach people how to use Replicache, not backend database design

The global counter is a risk to the first goal because it's a global lock. However we know from testing that our writes are about 20ms round trip, and that counts some network traffic, so the lock is smaller. At 20ms, we still support 50fps. If multiple people are doing things at the exact same time their writes will be lagged, but that's probably rare. Also, we might be able to go faster by moving to stored procs for the writes or making other changes.

Anyways, we can always complexity later if necessary.

## Details

* Create a `Cookie` table with one column `Version` of type `BIGINT NOT NULL`. Populate with version zero at schema creation time.
* Create a stored procedure `NextCookie()` that increments and returns this number
* Add new `Version` column to `Shape` table with a trigger on insert and update that calls this function.
* Add new `Deleted` `bool` column to `Shape`, default false
* The transactional model for push remains the same:
  * for each individual mutation
    * open a `serialized` transaction
    * validate incoming `lastMutationID`
    * execute transaction
      * because of triggers, any changes to shape will get a new version number
* The transactional model for pull remains the same, but we additionally now read the version field:
  * open a `serialized` transaction (but note we do no writes here, so this just gives us a consistent snapshot)
    * get lmid for client
    * get current cookie
    * get all the rows that have changed: `SELECT * FROM Shape WHERE Version > :cookieversion`
* Look into MySQL consistency settings and make sure we're using the right ones.
* Comment the code explaining that there are many strategies for calculating the changed rows with different tradeoffs depending on your needs - ideally this would point to an article but for now can tell them to check in with us and link to contact section of website.

**Comment by phritz** [comment]
generally SGTM
- recalling the comment on https://www.notion.so/fritz-wip-notes-digging-in-one-level-deeper-7abdd27d4f8348709195d3176aecefc8#e00a2d7c6e3740d39fd8131f02be0805, i need a little more information to convince myself there is no problem like described in the comment. can you add to the above:
  - how the cookie table is updated wrt the transaction that updates the lmid and shape? like can two pushes from different clients get interleaving values? is there anything stopping pushes from different clients from interleaving?
  - where the value for the cookie comes from when returning the pullrequest. like, how is it read and when?
- def agree your comment is important!
- can you confirm that for the sake of the demo the throughput is sufficient? you mention fps but in an aggregate context (updates in the db). like if 10 people are actively using it and an update takes 20ms then we get 1000ms/20ms/10 = 5 updates per second per user. i think the term 'fps' used outside of a single browser's context is a little confusing for me.

**Comment by aboodman** [comment]
> can you confirm that for the sake of the demo the throughput is sufficient? you mention fps but in an aggregate context (updates in the db). like if 10 people are actively using it and an update takes 20ms then we get 1000ms/20ms/10 = 5 updates per second per user. i think the term 'fps' used outside of a single browser's context is a little confusing for me.

I'm not sure. In order to answer this question I need to know the amt of time the lock is held inside MySQL *per mutation*. I need to measure that again. But I think it will be less than 20ms. Say it's 20ms -- that's 50 updates per second.

The way this demo works people aren't sending updates continuously -- it's extremely bursty.

I agree this part is a risk. It's so easy though I'm gonna try it first and just see.

**Comment by aboodman** [comment]
Basically this is the fastest path to getting rid of diff server, and if we end up doing the next most complicated thing for the cookie, there's little work lost.

**Comment by phritz** [comment]
SGTM thanks
